/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BiliIcon: typeof import('./src/components/BiliIcon.vue')['default']
    Directory_input: typeof import('./src/components/directory_input.vue')['default']
    File_upload: typeof import('./src/components/file_upload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User_snack: typeof import('./src/components/user_snack.vue')['default']
  }
}
