/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/audio_editor': RouteRecordInfo<'/audio_editor', '/audio_editor', Record<never, never>, Record<never, never>>,
    '/format_convert': RouteRecordInfo<'/format_convert', '/format_convert', Record<never, never>, Record<never, never>>,
    '/search_part': RouteRecordInfo<'/search_part', '/search_part', Record<never, never>, Record<never, never>>,
    '/setting_page': RouteRecordInfo<'/setting_page', '/setting_page', Record<never, never>, Record<never, never>>,
    '/spleeter_part': RouteRecordInfo<'/spleeter_part', '/spleeter_part', Record<never, never>, Record<never, never>>,
  }
}
